### ISSUE TITLE
Create a set of `core` tags for metadata that has niche applications across multiple rules packages

### ISSUE THREAD

**Issue by rsek** [rsek/datasworn#46]
Some of tags might warrant inclusion as full properties in the main schema. But doing every single one of these (especially for properties that are more about describing flavour), the schema could become bloated. Tags are a reasonable place to keep them for now.

Example tags that could be generalized:

```yaml
requires_deed:
  # for classic ironsworn assets that effectively require a deed
  description: |-
    This asset represents a notable achievement or situation in your story.
    It is not intended for a starting asset, but can be gained when you
    Advance after fulfilling its requirements.
  value_type: boolean
  applies_to: [asset]
requires_allies:
  description: |-
    This object requires allies to function, and is intended for co-op play, or
    guided play with allies. It is not appropriate for solo play.
  value_type: boolean
supernatural:
  description: |-
    This object is supernatural in nature, and is ideal for settings that
    feature supernatural or mythic powers.
  value_type: boolean
technological:
  description: |- 
    This object is technological in nature, and is ideal for settings that
    feature remarkable technologies.
  value_type: boolean
```
